### PR TITLE
Positioning and typings

### PR DESCRIPTION
**Pull request by questionablequestion**
#30 
#3

### CODE REVIEW

**Comment by questionablequestion** [comment]
Hey @prscX , have you had time to review this PR?

Btw. thanks for the lib. I have been searching for some good toast package that works well with modals and I have found this one, will use it in a future projects as well!

**Comment by arafatzahan** [comment]
Hahaha I also made a index.d.ts for personal use. Yours is better anyway. 

Also you are right that this is the only good toast library that works properly and supports custom styles. 

Wow, I didn't realize  this library was missing positions as everything else was working so well. Now I'm missing it already.Great work man 

LET'S GET THIS MERGED :D

**Comment by marudy** [comment]
This is much needed! Was looking for it as it was the only thing missing for my setup as well :) Thanks @questionablequestion and @arafatzahan .

@prscX I know how it goes with this being the project you maintain for free but this PR is super nice to have as soon as possible! I forked your repo just for this while I would prefer to use your maintained version!

Cheers and thanks guys

**Comment by arafatzahan** [comment]
This PR has a regression. Using it makes the bottom padding 0 so the toast is super close to bottom. We should pass a default offset value of some sorts if no offset is given.

**Comment by JerakRus** [comment]
@prscX It would really be great to combine this PR! I somehow implemented this function in my own code, but I'm not good at objective-c. Now, when updating react-native, my changes broke and I would like to switch back to the master branch! And if there is an opportunity to combine these changes, it would be great! Thank you in advance!)

**Comment by prscX** [comment]
Thanks @questionablequestion for all the Effort you have added for this PR.

I have merged the PR. Will validate it today, post which I will push the release.

Thanks
</ Pranav >

**Comment by prscX** [comment]
I have pushed the release [V1.0.2]. Let me know in case you face any issues.

@JerakRus: I have added defaut offsetY value at 50. Doing this it will not touch down to the bottom.

Thanks
</ Pranav >

**Pull request merged**
